spring:
  profiles:
    active: stage
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    defer-datasource-initialization: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true